
class GameConstants:
    PLAY_W_SILVER = 2
    CHAL_W_SILVER = 3
    CHAL_W_GOLD = 1
    PLAY_HINT_SILVERCOST = 1
    CHAL_HINT_SILVERCOST = 2
    HEART_GOLDCOST = 1
    MAX_LIVES = 3
    PASS_SILVERCOST = 3
    RESET_HEARTS_SECONDS = 6 * 3600

