class GameConstants:
    PLAY_W_SILVER = 2
    CHAL_W_SILVER = 3
    CHAL_W_GOLD = 1
    PLAY_HINT_SILVERCOST = 1
    CHAL_HINT_SILVERCOST = 2
    PASS_COINCOST = 3
    HEART_GOLDCOST = 1
    MAX_LIVES = 3